### ISSUE TITLE
一些改进建议

### ISSUE THREAD

**Issue by kxccc** [zzhirong/hop-zh-by-flypy#1]
1. hop 是支持 v d c y 这类可以跟跳转结合的命令，此插件不支持。
2. hop 通过双字符跳转时，可以在输入第一个字符后就按下 enter 键转为单字符跳转，在需要跳转到行末英文字符却用了双字符跳转时是有用的，此插件不支持。

**Comment by kxccc** [comment]
第一点不支持是因为此插件默认的 Keybindings 没有绑定，但试了绑定发现，对中文进行的范围操作中只有 v 是没问题的，其他 d c y 都是有问题的

**Comment by zzhirong** [comment]
> 1. hop 是支持 v d c y 这类可以跟跳转结合的命令，此插件不支持。

不知道有什么错误提示么? 是完全不能用还是有些字符不行? 能列出相关配置么? 比如告知`hop.nvim` 版本(`v2`好像有些问题, 具体我不记得是什么了, 所以我把版本锁定在 `v1`).

> 2. hop 通过双字符跳转时，可以在输入第一个字符后就按下 enter 键转为单字符跳转，在需要跳转到行末英文字符却用了双字符跳转时是有用的，此插件不支持。

确实不支持, 后续更新会加上, 记得需要设置`hop.nvim`的`char2_fallback_key`选项, 例如加上`char2_fallback_key = "<CR>"`到`hop.nvim`的配置文件中.

**Comment by kxccc** [comment]
这是一段配置，做了 f/F 的映射，演示 d 和 f/F 组合产生的问题，其他类似
```lua
return {
	{
		"phaazon/hop.nvim",
		version = "v1",
		event = { "VeryLazy" },
		config = function()
			require("hop").setup({
				char2_fallback_key = "<CR>",
				extensions = {
					"hop-zh-by-flypy",
				},
			})
		end,
	},
	{
		"zzhirong/hop-zh-by-flypy",
		event = { "VeryLazy" },
		dependencies = {
			"phaazon/hop.nvim",
		},
		config = function()
			local hop_zh_by_flypy = require("hop-zh-by-flypy")
			local directions = require("hop.hint").HintDirection

			vim.keymap.set("", "f", function()
				hop_zh_by_flypy.hint_char1({ direction = directions.AFTER_CURSOR, current_line_only = true })
			end, { remap = true })
			vim.keymap.set("", "F", function()
				hop_zh_by_flypy.hint_char1({ direction = directions.BEFORE_CURSOR, current_line_only = true })
			end, { remap = true })

			require("hop-zh-by-flypy").setup({
				set_default_mappings = false,
			})
		end,
	},
}
```

问题1:
此时，光标在最左边的空格，输入“dfga”，范围删除到第一个“更”
<img width="243" alt="截屏2023-04-10 23 42 47" src="https://user-images.githubusercontent.com/53963217/230938696-a7b0d9b4-0bf4-43ef-98df-a4c1ba84c5e7.png">
结果出现乱码
<img width="204" alt="截屏2023-04-10 23 43 06" src="https://user-images.githubusercontent.com/53963217/230938707-6f15050f-ec26-4ce4-810e-6b8f81e2c30a.png">

问题2:
此时，光标在最右边的空格，输入“dFya”，范围删除到第三个“云”
<img width="240" alt="截屏2023-04-10 23 43 41" src="https://user-images.githubusercontent.com/53963217/230940730-166375b4-77ba-4fd8-9a4a-bc28d8950061.png">
结果多了一个空格
<img width="161" alt="截屏2023-04-10 23 43 23" src="https://user-images.githubusercontent.com/53963217/230939935-3754af4d-43fa-401e-b762-b29cddcc1185.png">

**Comment by zzhirong** [comment]
最新的提交引入了新的 Bug, 撤回了, 明天再修改.

**Comment by zzhirong** [comment]
今早又做了些测试, 发现应该是`hop.nvim v1`的 bug, 我粗略查看了下它的 issue, 有一个 [issue](https://github.com/phaazon/hop.nvim/pull/315#issue-1372377971)提及了在多字节字符串(multi-byte chars)中跳转时会出错.

以下映射只用了`hop.nvim`中函数, 在`hop.nvim@v1` 版本中会出错.
```lua
-- 
local function map_f()
    local hop = require 'hop'
    local jump_target = require'hop.jump_target'
    local directions = require'hop.hint'.HintDirection
    -- local table = require'hop-zh-by-flypy.flypy_table'

    -- local pattern = table.char1pattern['g']
    local pattern = "更"

    local opts = {inclusive_jump=true, direction = directions.AFTER_CURSOR, current_line_only = true }

    opts = setmetatable(opts, {__index = hop.opts})
    local regex_jump_target = jump_target.regex_by_case_searching(pattern, false, opts)
    vim.keymap.set(
        "",
        "f",
        function()
            hop.hint_with(
                jump_target.jump_targets_for_current_line(regex_jump_target),
                opts
            )
        end,
        { noremap = true }
    )
end
map_f()
```
以下是测试文本内容:
```txt
云云云     更更更更
```

在安装`hop.nvim@v1`情况下, 运行以上代码, 然后在测试文本中按`fga`会出错.
然后我切换到`hop.nvim@master`, `fga`不出错, 但是, `dfa`又会出现乱码.

**Comment by zzhirong** [comment]
问题出在: https://github.com/phaazon/hop.nvim/blob/90db1b2c61b820e230599a04fedcd2679e64bd07/lua/hop/init.lua#L287
源码如下:
```lua
if vim.api.nvim_get_mode().mode == 'no' and direction ~= 1 then
    column = column + 1
end
```
`colum + 1` 如果在全部都是单字节字符的时候是没问题的, 如果碰到多字节字符, 终点会指向多字节字符的第一个字节, 所以以上执行完`dfg`后出现乱码就可以解释通了.

我做了些简单的修改, 源码在`https://github.com/zzhirong/hop.nvim`, 你可以试试看修改之后的效果.

**Comment by kxccc** [comment]
感谢，目前觉得支持 normal 模式跳转和 visual 模式选择已经很方便使用了
仔细想想之前的第二点建议，也觉得实用性不大😂

**Comment by zzhirong** [comment]
其实我还发现`hop.nvim`有其它 Bug(比如我到现在`F`都还是有问题), 作者半年都没有更新了, issue 一大堆也没有处理, PR 也不合并, 估计把它抛弃了, 我打算用回`easymotion`, 当初转到这个插件, 是看中它在`vscode-neovim`中也能用, 另外, 它不会在进入选择模式的时惊动 linter, 但架不住 bug 真多. 我也为`easymotion`写过一个对应的插件"[zzhirong/vim-easymotion-zh](https://github.com/zzhirong/vim-easymotion-zh)", 和这个插件一个效果.
