### ISSUE TITLE
提醒：不能使用 smoka7 的hop.nvim

### ISSUE THREAD

**Issue by cycode0527** [zzhirong/hop-zh-by-flypy#2]
如题，不是bug 提醒，只是我折腾了半天，发现总是缺少一些函数。最后发现 smoka7 的hop.nvim 优化了一些函数是没有的。
只是提醒各位下载此插件的人罢了，目前还在体验这个插件中

**Comment by zzhirong** [comment]
推荐用 [vim-easymotion-zh](https://github.com/zzhirong/vim-easymotion-zh), 我这个插件已经很久(1 年)没用了, 我目前主力还是 [easymotion](https://github.com/easymotion/vim-easymotion). 我不记得当时为什么弃用 hop.nvim 了.
