### ISSUE TITLE
能实现中英混用吗？

### ISSUE THREAD

**Issue by xuwei152** [zzhirong/hop-zh-by-flypy#3]
希望能实现类似如下面的功能：

按下f然后按下c 则c开头的单词和拼音为c开通的汉字都被标出来。

**Comment by zzhirong** [comment]
目前的状态, 你说的功能已经实现了呀, 能贴下你的配置么? 或者简单点, 可以贴出你的`f`键映射状态么?(通过命令`:nmap f`就可以得到了)

**Comment by xuwei152** [comment]
不好意思确实是已经支持了，是我设置的问题。

但是有字管用有些不管用。
比如对于如下的代码片段

![Clip_2024-07-06_23-44-08](https://github.com/zzhirong/hop-zh-by-flypy/assets/51861161/d190cdb8-cc28-41d8-a165-2ea4b74e376b)

f+b  是正常的“本” 和b字母都被标出来了
![Clip_2024-07-06_23-44-46](https://github.com/zzhirong/hop-zh-by-flypy/assets/51861161/29df92b2-f2ac-49ca-a194-2b4c5fcd22ad)

f+z  "注"字却没标出来如下图。
![Clip_2024-07-06_23-46-15](https://github.com/zzhirong/hop-zh-by-flypy/assets/51861161/93a92740-19a6-4438-8b36-1a45d346e269)

其他的双辅音也不管用，如“射” “常”。

我的配置如下
```lua
{
    'zzhirong/hop-zh-by-flypy',
    dependencies = {
      'phaazon/hop.nvim',
    },
    config = function()
      local hop_flypy = require "hop-zh-by-flypy"
      hop_flypy.setup({
        -- 注意: 本扩展的默认映射覆盖掉了一些常用的映射: f, F, t, T, s
        -- 设置 set_default_mappings 为 false 可关闭默认映射.
        set_default_mappings = true,
      })
      vim.keymap.set('n', 'f', '<cmd>HopFlypy1<CR>')
    end
  }
```

![Clip_2024-07-06_23-49-36](https://github.com/zzhirong/hop-zh-by-flypy/assets/51861161/5f81e605-21ed-4808-99f2-8b4b0eae7202)

**Comment by zzhirong** [comment]
把汉字转换成 2 字母编码使用的是小鹤双拼的编码方案, 所`注(zhu)`对应的编码是`vu`, 而不是`zu`. 

至于为什么使用小鹤双拼, 首先它刚好是双拼方案, 所以所有汉字都可以对应一个两个字母的编码, 其次, 我主力中文打字方案就是小鹤音形.

至于声母`zh`为为什么不在按键`z`上, 我想是因为以声母`z`和`zh`开头的汉字很多, 所以, 如果两个声母都指定到`z`键上, 重码会很多,  而把`zh`指定到`v`键上, 可以有效减少重码. 

熟悉小鹤双拼方案的话, 需要花点时间(大约半小时). [小鹤双拼官网](https://www.flypy.com/)
